# Generated by Django 4.1 on 2022-09-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0002_alter_finca_nitfinca'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='apellidoGerente',
            field=models.CharField(default='', max_length=100),
        ),
    ]
