# Generated by Django 4.1 on 2022-09-17 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0004_alter_categmaterial_options_alter_proveedor_options'),
        ('appGerente', '0003_finca_apellidogerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacLote', models.CharField(max_length=300, null=True)),
                ('descripLote', models.CharField(max_length=100)),
                ('areaLote', models.IntegerField()),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
    ]
