# Generated by Django 4.1 on 2022-09-17 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0004_alter_categmaterial_options_alter_proveedor_options'),
        ('appGerente', '0004_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefonoCliente', models.CharField(max_length=20)),
                ('nitCliente', models.CharField(max_length=20)),
                ('direccionCliente', models.CharField(max_length=200)),
                ('correoCliente', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSiembra', models.DateField(default=datetime.date.today)),
                ('fechaCosecha', models.DateField(default=datetime.date.today)),
                ('cantidadCosecha', models.IntegerField(default=0)),
                ('observacCultivo', models.CharField(max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.lote')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existenciaEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorUnitarioEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deprecEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.equipo')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existenciaInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorUnitarioInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.insumo')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existenciaProducto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripProducto', models.CharField(max_length=200)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFactura', models.CharField(max_length=20)),
                ('fechaVenta', models.DateField(default=datetime.date.today)),
                ('cantidadVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorTotalventa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacVenta', models.CharField(max_length=200, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTrabajador', models.CharField(max_length=100)),
                ('telefonoTrabajador', models.CharField(max_length=20)),
                ('nitTrabajador', models.CharField(max_length=20)),
                ('emailTrabajador', models.CharField(max_length=100)),
                ('costoHoraTrabajador', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rol', models.IntegerField(default=0)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.CreateModel(
            name='InsumosLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadUsadaInsumo', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cultivo')),
                ('insumoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.insumofinca')),
            ],
        ),
        migrations.CreateModel(
            name='Indirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField(default=datetime.date.today)),
                ('numFactura', models.CharField(max_length=20)),
                ('observacPago', models.CharField(max_length=200)),
                ('valorPagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca')),
            ],
        ),
        migrations.CreateModel(
            name='HorasTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacLabor', models.CharField(max_length=200, null=True)),
                ('tipoTrabajo', models.CharField(max_length=20, null=True)),
                ('fechaLabor', models.DateField(default=datetime.date.today)),
                ('duracionLabor', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categHoras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.categhoras')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cultivo')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='EquiposLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadUsadaEquipo', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.cultivo')),
                ('equipoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.equipofinca')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.producto'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida'),
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompraInsumo', models.DateField(default=datetime.date.today)),
                ('numFactura', models.CharField(max_length=20)),
                ('cantidadCompraInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorCompraInsumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.insumo')),
                ('insumoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.insumofinca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompraEquipo', models.DateField(default=datetime.date.today)),
                ('numFactura', models.CharField(max_length=20)),
                ('cantidadCompraEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorCompraEquipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.equipo')),
                ('equipoFinca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGerente.equipofinca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.proveedor')),
            ],
        ),
    ]
