# Generated by Django 4.1 on 2022-09-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
