# Generated by Django 4.1 on 2022-09-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGerente', '0001_initial'),
        ('appUsuarios', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGerente.finca'),
        ),
    ]
