# Generated by Django 4.1 on 2022-09-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsuarios', '0003_usuarios_finca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
