# Generated by Django 4.1 on 2022-09-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripCategMaterial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripEquipo', models.CharField(max_length=100)),
                ('categMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.categmaterial')),
            ],
        ),
    ]
