# Generated by Django 4.1 on 2022-09-17 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripCategHora', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias de Horas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefonoProveedor', models.IntegerField(null=True)),
                ('nombreProveedor', models.CharField(max_length=100)),
                ('nitProveedor', models.CharField(max_length=20)),
                ('direccionProveedor', models.CharField(max_length=200)),
                ('correoProveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripUnidadMedida', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Undades de medida',
            },
        ),
        migrations.AlterModelOptions(
            name='categmaterial',
            options={'verbose_name_plural': 'Categorias Material'},
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripInsumo', models.CharField(max_length=100)),
                ('categMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.categmaterial')),
                ('unidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.unidadmedida')),
            ],
        ),
    ]
