# Generated by Django 4.1 on 2022-09-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0003_categhoras_recargo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categmaterial',
            options={'verbose_name_plural': 'Categorias de Material y equipo'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
